CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done boolean,
    projectid integer REFERENCES projects(id)
);

insert into projects (name, priority, description, deliverydate) values ('Made a Web App', 1, 'Using Javascript', '2020-05-01');
insert into projects (name, priority, description, deliverydate) values ('Made an App', 1, 'Using React Native', '2020-05-10');
insert into projects (name, priority, description, deliverydate) values ('Made a Desktop App', 1, 'Using C++', '2020-05-14');

select * from projects;

insert into tasks (name, done, projectid) values ('Download Vuejs', false, 1);
insert into tasks (name, done, projectid) values ('Create UI Web', false, 1);
insert into tasks (name, done, projectid) values ('Download Expo', false, 2);
insert into tasks (name, done, projectid) values ('Design UI', false, 2);

select * from tasks;